revenue_grain:
  target: ci
  outputs:
    ci:
      type: duckdb
      path: ci.duckdb
      threads: 4
      extensions:
        - tpch
    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4
      extensions:
        - tpch
